function plotqs(x,y,a,b,c)
% PLOTQS Plot quadratic spline generated by QUADSPLINE.
% Example:  Do "help quadspline" to see an example.

n = length(x) - 1;   % = number of subintervals
for k = 1:n
    xx = linspace(x(k),x(k+1),21);  % choose fine grid in each subinterval
    plot(xx,a(k) + b(k)*(xx-x(k)) + c(k)*(xx-x(k)).*(xx-x(k+1)),'k');
    hold on
end
hold off
xlabel x

